"""refactor task dependencies to PMBOK standard

Revision ID: 6a9f06ad5a33
Revises: ed33bac01aed
Create Date: 2026-03-29 22:09:47.271777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9f06ad5a33'
down_revision: Union[str, None] = 'ed33bac01aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    dependency_enum = sa.Enum('FINISH_TO_START', 'START_TO_START', 'FINISH_TO_FINISH', 'START_TO_FINISH', name='dependencytype')
    dependency_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('task_dependencies', sa.Column('predecessor_id', sa.UUID(), nullable=False))
    op.add_column('task_dependencies', sa.Column('successor_id', sa.UUID(), nullable=False))
    op.add_column('task_dependencies', sa.Column('type', dependency_enum, nullable=False))
    op.add_column('task_dependencies', sa.Column('lag_days', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('task_dependencies_task_id_fkey'), 'task_dependencies', type_='foreignkey')
    op.drop_constraint(op.f('task_dependencies_depends_on_id_fkey'), 'task_dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'task_dependencies', 'tasks', ['successor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_dependencies', 'tasks', ['predecessor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_dependencies', 'depends_on_id')
    op.drop_column('task_dependencies', 'task_id')
    op.drop_column('task_dependencies', 'dependency_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_dependencies', sa.Column('dependency_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('task_dependencies', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('task_dependencies', sa.Column('depends_on_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_dependencies', type_='foreignkey')
    op.drop_constraint(None, 'task_dependencies', type_='foreignkey')
    op.create_foreign_key(op.f('task_dependencies_depends_on_id_fkey'), 'task_dependencies', 'tasks', ['depends_on_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('task_dependencies_task_id_fkey'), 'task_dependencies', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_dependencies', 'lag_days')
    op.drop_column('task_dependencies', 'type')
    op.drop_column('task_dependencies', 'successor_id')
    op.drop_column('task_dependencies', 'predecessor_id')

    dependency_enum = sa.Enum('FINISH_TO_START', 'START_TO_START', 'FINISH_TO_FINISH', 'START_TO_FINISH', name='dependencytype')
    dependency_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
